package ca.bcit.comp2522.step_04_events_part_1;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.text.Text;
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;

/**
 * A variation on the PushCounter program that uses a full EventHandler class.
 * 
 * @author Lewis & Loftus 9e
 * @author BCIT
 * @version 2022
 */
public class PushCounter2 extends Application {
    // Records the number of times the button is pressed.
    private int count;

    // Displays the number of times the button is pressed.
    private Text countText;

    /**
     * Displays a GUI containing a button and text that displays how many times
     * the button is pushed.
     * 
     * @param primaryStage a Stage
     */
    public void start(Stage primaryStage) {
        count = 0;
        countText = new Text("Pushes: 0");

        Button push = new Button("Push Me!");

        // We pass an anonymous object to the set method
        push.setOnAction(new ButtonHandler()); // This is different! Neat-o!

        FlowPane pane = new FlowPane(push, countText);
        pane.setAlignment(Pos.CENTER);

        final int horizontalGap = 20;
        pane.setHgap(horizontalGap);
        pane.setStyle("-fx-background-color: lightgrey");
        
        final int appWidth = 300;
        final int appHeight = 100;
        Scene scene = new Scene(pane, appWidth, appHeight);

        primaryStage.setTitle("PushCounter Version 2");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    /**
     * ButtonHandler is an inner class that handles the ActionEvent
     * generated by the Button in PushCounter.
     * 
     * @author Lewis & Loftus 9e
     * @author BCIT
     * @version 2019
     */
    private class ButtonHandler implements EventHandler<ActionEvent> {

        /**
         * Handles the event.
         * 
         * @param event invokes this method
         */
        public void handle(ActionEvent event) {
            count++;
            countText.setText("Pushes: " + count);
        }
    }

    /**
     * Launches the JavaFX application.
     *
     * @param args command line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }

}

